name: Jira Find issue key
description: Find an issue inside event
branding:
  icon: 'book-open'
  color: 'blue'
inputs:
  string:
    description: Provide a string to extract issue key from
    required: false
  from:
    description: Find from predefined place (should be either 'branch', or 'commits')
    required: false
    default: commits
outputs:
  issue:
    description: Key(s) of the found issue(s) - comma-separated if multiple
  issues:
    description: Comma-separated list of all found issue keys (same as issue output)
runs:
  using: 'node20'
  main: './dist/index.js'
